name: GitHub Actions ITnews
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build:prod
      - name: Linting typescript
        run: npm run lint:ts
      - name: Linting css
        run: npm run lint:scss
      - name: Unit testing
        run: npm run test:unit
      - name: Build storybook
        run: npm run storybook:build
      - name: Screenshot testing
        run: npm run test:ui:ci